# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow3.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(662, 484)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 10, 661, 411))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.label_7 = QtWidgets.QLabel(self.home)
        self.label_7.setGeometry(QtCore.QRect(460, 20, 121, 16))
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.home)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 47, 13))
        self.label_6.setObjectName("label_6")
        self.et_publish_blog = QtWidgets.QPlainTextEdit(self.home)
        self.et_publish_blog.setGeometry(QtCore.QRect(20, 310, 341, 61))
        self.et_publish_blog.setObjectName("et_publish_blog")
        self.btn_publish_blog = QtWidgets.QPushButton(self.home)
        self.btn_publish_blog.setGeometry(QtCore.QRect(370, 310, 71, 31))
        self.btn_publish_blog.setObjectName("btn_publish_blog")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.home)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(460, 40, 161, 261))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lw_active_peers = QtWidgets.QListView(self.horizontalLayoutWidget_4)
        self.lw_active_peers.setEnabled(True)
        self.lw_active_peers.setObjectName("lw_active_peers")
        self.horizontalLayout_5.addWidget(self.lw_active_peers)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.home)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(20, 40, 421, 261))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lw_blogs = QtWidgets.QListView(self.horizontalLayoutWidget_5)
        self.lw_blogs.setObjectName("lw_blogs")
        self.horizontalLayout_6.addWidget(self.lw_blogs)
        self.btn_get_my_blog = QtWidgets.QPushButton(self.home)
        self.btn_get_my_blog.setGeometry(QtCore.QRect(300, 10, 141, 31))
        self.btn_get_my_blog.setObjectName("btn_get_my_blog")
        self.tabWidget_2.addTab(self.home, "")
        self.peerlist = QtWidgets.QWidget()
        self.peerlist.setObjectName("peerlist")
        self.label_8 = QtWidgets.QLabel(self.peerlist)
        self.label_8.setGeometry(QtCore.QRect(20, 20, 171, 16))
        self.label_8.setObjectName("label_8")
        self.btn_subscribe_user = QtWidgets.QPushButton(self.peerlist)
        self.btn_subscribe_user.setEnabled(False)
        self.btn_subscribe_user.setGeometry(QtCore.QRect(400, 40, 151, 23))
        self.btn_subscribe_user.setObjectName("btn_subscribe_user")
        self.btn_block_user = QtWidgets.QPushButton(self.peerlist)
        self.btn_block_user.setEnabled(False)
        self.btn_block_user.setGeometry(QtCore.QRect(400, 70, 151, 23))
        self.btn_block_user.setObjectName("btn_block_user")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.peerlist)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(20, 40, 351, 271))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lw_peer_list = QtWidgets.QListView(self.horizontalLayoutWidget_6)
        self.lw_peer_list.setObjectName("lw_peer_list")
        self.horizontalLayout_7.addWidget(self.lw_peer_list)
        self.tabWidget_2.addTab(self.peerlist, "")
        self.inbox = QtWidgets.QWidget()
        self.inbox.setObjectName("inbox")
        self.comboBox_2 = QtWidgets.QComboBox(self.inbox)
        self.comboBox_2.setGeometry(QtCore.QRect(360, 230, 251, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_11 = QtWidgets.QLabel(self.inbox)
        self.label_11.setGeometry(QtCore.QRect(20, 20, 101, 16))
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLabel(self.inbox)
        self.label_10.setGeometry(QtCore.QRect(360, 20, 47, 13))
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(self.inbox)
        self.label_9.setGeometry(QtCore.QRect(360, 210, 47, 13))
        self.label_9.setObjectName("label_9")
        self.pushButton_4 = QtWidgets.QPushButton(self.inbox)
        self.pushButton_4.setGeometry(QtCore.QRect(540, 260, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.inbox)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(20, 40, 331, 261))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.listWidget_4 = QtWidgets.QListWidget(self.horizontalLayoutWidget_7)
        self.listWidget_4.setObjectName("listWidget_4")
        self.horizontalLayout_8.addWidget(self.listWidget_4)
        self.verticalScrollBar_7 = QtWidgets.QScrollBar(self.horizontalLayoutWidget_7)
        self.verticalScrollBar_7.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_7.setObjectName("verticalScrollBar_7")
        self.horizontalLayout_8.addWidget(self.verticalScrollBar_7)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.inbox)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(360, 40, 251, 161))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget_8)
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.horizontalLayout_9.addWidget(self.plainTextEdit_4)
        self.tabWidget_2.addTab(self.inbox, "")
        self.blockusr = QtWidgets.QWidget()
        self.blockusr.setObjectName("blockusr")
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.blockusr)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(30, 50, 591, 141))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.listWidget_5 = QtWidgets.QListWidget(self.horizontalLayoutWidget_9)
        self.listWidget_5.setObjectName("listWidget_5")
        self.horizontalLayout_10.addWidget(self.listWidget_5)
        self.verticalScrollBar_8 = QtWidgets.QScrollBar(self.horizontalLayoutWidget_9)
        self.verticalScrollBar_8.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_8.setObjectName("verticalScrollBar_8")
        self.horizontalLayout_10.addWidget(self.verticalScrollBar_8)
        self.label_12 = QtWidgets.QLabel(self.blockusr)
        self.label_12.setGeometry(QtCore.QRect(30, 20, 121, 16))
        self.label_12.setObjectName("label_12")
        self.pushButton_6 = QtWidgets.QPushButton(self.blockusr)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 240, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.comboBox_3 = QtWidgets.QComboBox(self.blockusr)
        self.comboBox_3.setGeometry(QtCore.QRect(30, 210, 341, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.tabWidget_2.addTab(self.blockusr, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_8)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(90, 60, 160, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout.addWidget(self.listWidget)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 350, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_8.setGeometry(QtCore.QRect(400, 350, 75, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_8)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(360, 60, 160, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listWidget_2 = QtWidgets.QListWidget(self.horizontalLayoutWidget_2)
        self.listWidget_2.setObjectName("listWidget_2")
        self.horizontalLayout_2.addWidget(self.listWidget_2)
        self.label_2 = QtWidgets.QLabel(self.tab_8)
        self.label_2.setGeometry(QtCore.QRect(360, 30, 201, 16))
        self.label_2.setObjectName("label_2")
        self.tabWidget_2.addTab(self.tab_8, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 662, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "Aktif Kullanıcılar"))
        self.label_6.setText(_translate("MainWindow", "Yayınlar"))
        self.btn_publish_blog.setText(_translate("MainWindow", "Yayınla"))
        self.btn_get_my_blog.setText(_translate("MainWindow", "Kendi Yayınlarım"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.home), _translate("MainWindow", "Home"))
        self.label_8.setText(_translate("MainWindow", "Ağda olan peer\'ların listesi"))
        self.btn_subscribe_user.setText(_translate("MainWindow", "Abone Ol"))
        self.btn_block_user.setText(_translate("MainWindow", "Engelle"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.peerlist), _translate("MainWindow", "Network Peer List"))
        self.label_11.setText(_translate("MainWindow", "Gelen Kutusu"))
        self.label_10.setText(_translate("MainWindow", "Mesaj"))
        self.label_9.setText(_translate("MainWindow", "Kime"))
        self.pushButton_4.setText(_translate("MainWindow", "Yolla"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.inbox), _translate("MainWindow", "Inbox"))
        self.label_12.setText(_translate("MainWindow", "Engellenmiş Peer Listesi"))
        self.pushButton_6.setText(_translate("MainWindow", "Engelli Kaldır"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.blockusr), _translate("MainWindow", "Blocked Users"))
        self.pushButton_2.setText(_translate("MainWindow", "Engelle"))
        self.pushButton_8.setText(_translate("MainWindow", "Onayla"))
        self.label_2.setText(_translate("MainWindow", "Bana abone olanlar"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "Requests"))

